FROM node:20-alpine AS builder
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app

COPY --from=builder /app /app

RUN chown -R 1000:1000 /app

RUN addgroup -g 1000 nextgroup \
    && adduser -D -u 1000 -G nextgroup nextjs

USER nextjs

ENV NODE_ENV=production
EXPOSE 3000

CMD ["npm", "start"]
