FROM node:20-alpine AS builder
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app

RUN addgroup nextgroup && adduser -D -G nextgroup nextjs

USER nextjs

COPY --chown=nextjs:nextgroup --from=builder /app /app

ENV NODE_ENV=production
EXPOSE 3000

CMD ["npm", "start"]
